### ISSUE TITLE
Adapt to production MQTT protocol

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/node-app-sdk#1]
See https://github.com/TheThingsNetwork/ttn/tree/refactor/mqtt

**Comment by FokkeZB** [comment]
@johanstokking, @htdvisser may I have your input on these changes for node-ttn to work with production?

Changes in the message formats:
- [x] [downlink](https://github.com/TheThingsNetwork/ttn/tree/refactor/mqtt#downlink-messages)
  - `payload` > `payload_raw`
  - no more `ttl`
- [x] [uplink](https://github.com/TheThingsNetwork/ttn/tree/refactor/mqtt#uplink-messages)
  - `fields` > `payload_fields`
  - `payload` > `payload_raw`
  - Include full `metadata` array, not just first object in array
  - Inject Dev EUI as `dev_eui` instead of `devEUI`, like MQTT does in activations
- [x] [activation](https://github.com/TheThingsNetwork/ttn/tree/refactor/mqtt#device-activations)
  - Pass on full message instead of just `devEUI`, which also means this is now `dev_eui`.

Changes in the broker address
- [x] If `staging.thethingsnetwork.org` is give, enable legacy flag so the library continuous to work with those message formats
- ~~If we will have a default production broker, make that constructor argument optional.~~
- [x] Allow the user to just give the region and compose the broker URL in the constructor.

Other improvements while we're at it:
- [x] [connect](https://www.npmjs.com/package/mqtt#event-connect)
  - Pass along `connack` argument?
- [x] [end](https://www.npmjs.com/package/mqtt#end)
  - Send along the optional `force` and `cb` options?

**Comment by htdvisser** [comment]
The URLs for the Load Balancers of our datacenters are currently as follows:
- `eu.thethings.network`
- `us-west.thethings.network`
- `brazil.thethings.network`
- `se-asia.thethings.network`

We might want to create additional CNAMES for mqtt/router/broker/handler, but maybe the plain URLs are more clear?

**Comment by FokkeZB** [comment]
Thanks @htdvisser, I'd suggest that the Client constructor will accept:
- `'eu.thethings.network', 'app id', 'app key'`
- `'eu', 'app id', 'app key'`: when the first arg doesn't contain a `.` it will add `.thethings.network`
- `'app id', 'app key'`: when the first arg is skipped it defaults to `eu.thethings.network`

We just need to be sure that the we never introduce something like `us.west` but always stick to dashes, just like Amazon does.

**Comment by htdvisser** [comment]
I think defaulting to `eu` (last bullet) is a bad idea. Applications can only be registered with one handler, and therefore messages will only arrive on one MQTT broker. Users should explicitly pass the region.

**Comment by FokkeZB** [comment]
Clear, thx!

**Comment by FokkeZB** [comment]
As part of the refactor I've simplified the API

https://github.com/TheThingsNetwork/node-ttn/blob/refactor/src/example.js
- `Client(broker, appEUI, accessKey)` > `Client(region, appId, accessKey)`
- `uplink` -> `message`
- `downlink()` -> `send()`

For discussion on standardising on a simple API for SDKs:

https://docs.google.com/document/d/1nk6_Tty1WZ3RCl0hOVspLq6h87ZrQQiL2OjFguNdK7s/edit?usp=sharing
