### ISSUE TITLE
Add support to subscribe to a specific topic

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/node-app-sdk#9]
For example: `/+/devices/+/up/temperature`.

The challenge is that if the topic comes in the `+` are the actual app/device IDs so unless we duplicate MQTT's wildcard matching it's hard to map it to an event with the same name. Probably best to have a single event much like MQTT's [message](https://www.npmjs.com/package/mqtt#event-message) which includes the topic.

**Comment by FokkeZB** [comment]
Possible API:

```
// subscribe to a field (of optional specific device)
client.on('field', fieldPath, [deviceId], function(deviceId, field, payload) {
});

// subscribe to messages (of optional specific device)
client.on('message', [deviceId], function(deviceId, payload) {
});
```

What might be confusing is that - unless we handle field/deviceID mapping internally - if you'd use these APIs multiple times each callback would be called for any field/message topic.

**Comment by FokkeZB** [comment]
As per @johanstokking's suggestion on Slack we'll keep it simple and allow the user to optionally filter on a single or array of devices and to filter on a specific field.

**Comment by johanstokking** [comment]
Yep, I'd say one method:

```
client.on('message', [devices], [field], function(deviceId, fields, payload) {
});
```

If `[devices]` is set, and either a string or an array, subscribe to that device or devices. Otherwise, subscribe to `+`. If `[field]` is set, subscribe to that field, otherwise subscribe to `up`.

Note that, when subscribing to a field, the `fields` parameter in the callback becomes a bit useless. When subscribing to the field `temperature`, we might want to have `{ temperature: payload }` in there, just for consistency with the general `up` topic.
